enum NeoScope {
	Auth = 'auth',
	UserInfo = 'userinfo',
	Timeline = 'timeline',
	UserBook = 'userbook',
	Audience = 'audience',
	Explorer = 'explorer',
	Blog = 'blog',
	CollaborativeWall = 'collaborativewall',
	CAS = 'cas',
	LVS = 'lvs',
	Conversation = 'conversation',
	Formulaire = 'formulaire',
	Homeworks = 'homeworks',
	Mediacentre = 'mediacentre',
	Actualites = 'actualites',
	Pronote = 'pronote',
	SchoolBook = 'schoolbook',
	Scrapbook = 'scrapbook',
	Edt = 'edt',
	VieScolaire = 'viescolaire',
	Diary = 'diary',
	Presences = 'presences',
	Wiki = 'wiki',
	Workspace = 'workspace',
	Infra = 'infra',
	Directory = 'directory',
	Portal = 'portal',
	SSO = 'sso',
	Zimbra = 'zimbra',
	Incidents = 'incidents',
	Competences = 'competences',
	Support = 'support',
}

export { NeoScope };